### ISSUE TITLE
Build failure due to missing extension files

### ISSUE THREAD

**Issue by gforsyth** [conda-forge/duckdb-engine-feedstock#17]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

the 0.6.0 release is failing because of `test_preload_extension` failing to find an expected extension file that is 404ing

```
=================================== FAILURES ===================================
____________________________ test_preload_extension ____________________________

    @mark.skipif(os.uname().machine == "aarch64", reason="not supported on aarch64")
    def test_preload_extension() -> None:
>       duckdb.default_connection.execute("INSTALL httpfs")
E       RuntimeError: IO Error: Failed to download extension http://extensions.duckdb.org/c1bb9f6/linux_amd64/httpfs.duckdb_extension.gz
```

@mause are we just being impatient about those extension files?  Or is this test failure spurious?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by Mause** [comment]
Okay, looks like the conda duckdb version is being built wrong - the git sha hash in the URL corresponds to https://github.com/conda-forge/python-duckdb-feedstock/commit/c1bb9f667eee001e09b3913aa3cf08d56cd33688 which it absolutely should not

**Comment by Mause** [comment]
This basically means extensions are unusable in the conda build of duckdb

**Comment by gforsyth** [comment]
that seems like a problem.  I'll take a look.  thanks @mause!

**Comment by gforsyth** [comment]
Fixed upstream
